language: python
python:
  - "2.7"

sudo: required
services:
  - docker

env:
  matrix:
    - ZEPHYR_SRC=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.9/zephyr-sdk-0.9-setup.run TAG="0.9.0" BRANCH="master" LATEST=1
  # we are not running a test for 0.8.1, because the zephyr.bin binary
  # cannot be generated out-of-tree with Zephyr 1.4.0
  # - ZEPHYR_SRC=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.8.1-i686/zephyr-sdk-0.8.1-i686-setup.run TAG="0.8.1" BRANCH="v1.4.0"

  global:
    - REPO=zephyriot/zephyr-container

before_install:
  # list available docker-engine versions
  - apt-cache madison docker-engine

script:
  - docker version
  - ./scripts/build_zephyr_container
  - ./scripts/build_zephyr_app

after_success:
  - bash deploy.sh

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
